#!/usr/bin/env node

/**
 * Reads package.json and regenerates the auto-generated sections of README.md
 * (Extension Settings and Commands) so they stay in sync with the manifest.
 *
 * Usage:
 *   node scripts/update-readme.mjs          # update README.md in place
 *   node scripts/update-readme.mjs --check  # exit 1 if README is out of date
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const PKG_PATH = resolve(ROOT, "package.json");
const README_PATH = resolve(ROOT, "README.md");

const pkg = JSON.parse(readFileSync(PKG_PATH, "utf-8"));

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDefault(schema) {
  const val = schema.default;
  if (schema.type === "array") return "`[]`";
  if (schema.type === "boolean") return `\`${val}\``;
  if (schema.type === "string") return val === "" ? '`""`' : `\`"${val}"\``;
  return `\`${JSON.stringify(val)}\``;
}

function formatType(schema) {
  if (schema.type === "array") return `\`${schema.items?.type ?? "string"}[]\``;
  return `\`${schema.type}\``;
}

// ── Section generators ────────────────────────────────────────────────────────

function generateSettings() {
  const props = pkg.contributes?.configuration?.properties ?? {};
  const rows = Object.entries(props).map(([key, schema]) => {
    return `| \`${key}\` | ${formatType(schema)} | ${formatDefault(schema)} | ${schema.description} |`;
  });

  return [
    "## Extension Settings",
    "",
    "| Setting | Type | Default | Description |",
    "|---------|------|---------|-------------|",
    ...rows,
  ].join("\n");
}

function generateCommands() {
  const cmds = pkg.contributes?.commands ?? [];
  const rows = cmds.map((c) => `| ${c.title} | ${c.description ?? c.title} |`);

  return [
    "## Commands",
    "",
    "All commands are available from the **C# Tests** sidebar and the Command Palette (prefix `C# Test Explorer`).",
    "",
    "| Command | Description |",
    "|---------|-------------|",
    ...rows,
  ].join("\n");
}

// ── Replace between markers ──────────────────────────────────────────────────

function replaceSection(readme, tag, content) {
  const startMarker = `<!-- AUTO:${tag}:START`;
  const endMarker = `<!-- AUTO:${tag}:END -->`;

  const startIdx = readme.indexOf(startMarker);
  const endIdx = readme.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    console.error(`Missing markers for AUTO:${tag} in README.md`);
    process.exit(1);
  }

  const before = readme.substring(0, startIdx);
  const after = readme.substring(endIdx + endMarker.length);

  const newStartComment = `${startMarker} — generated by scripts/update-readme.mjs, do not edit manually -->`;
  return `${before}${newStartComment}\n${content}\n${endMarker}${after}`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

let readme = readFileSync(README_PATH, "utf-8");

readme = replaceSection(readme, "SETTINGS", generateSettings());
readme = replaceSection(readme, "COMMANDS", generateCommands());

const checkMode = process.argv.includes("--check");

if (checkMode) {
  const current = readFileSync(README_PATH, "utf-8");
  if (current !== readme) {
    console.error(
      "README.md is out of date. Run `npm run readme:update` to fix it.",
    );
    process.exit(1);
  }
  console.log("README.md is up to date.");
} else {
  writeFileSync(README_PATH, readme, "utf-8");
  console.log("README.md updated.");
}
